name: CRON
on:
    schedule:
      - cron: '15 23 * * *'
jobs:
  cron:
    services:
      selenium: 
        image: selenium/standalone-chrome:4
        ports:
        - 4444/tcp
        options: --health-cmd '/opt/bin/check-grid.sh'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.4.0]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1
      - name: Daily check in
        env:
          WEBDRIVER_HOST: localhost
          WEBDRIVER_PORT: ${{ job.services.selenium.ports[4444] }}
        run: julia --proj -e 'using Pkg; Pkg.instantiate(); using COVID_Tracking_Clean; givenname = "José Bayoán";
                              surname = "Santiago Calderón"; division = "SDAD"; health = "good"; email = "jbs3hp@virginia.edu";
                              wd = RemoteWebDriver(Capabilities("chrome"), host = get(ENV, "WEBDRIVER_HOST", "localhost"),
                                                   port = parse(Int, get(ENV, "WEBDRIVER_PORT", "4444")),
                                                   path = "");
                              checkin(wd, givenname, surname, division, health, email = email);'
